<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tamp.Observer.Storage.Postgres</RootNamespace>
    <AssemblyName>Tamp.Observer.Storage.Postgres</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tamp.Observer.Domain\Tamp.Observer.Domain.csproj" />
  </ItemGroup>

</Project>
