/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectLatency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IngestedLog: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            serviceId?: string;
            /** Format: uuid */
            environmentId?: null | string;
            /** Format: uuid */
            versionId?: string;
            /** Format: int64 */
            timeUnixNano?: number | string;
            /** Format: int32 */
            severityNumber?: number | string;
            severityText?: null | string;
            body?: null | string;
            traceId?: null | string;
            spanId?: null | string;
            instanceId?: string;
            attributes?: {
                [key: string]: string;
            };
            receiptId: string;
            /** Format: date-time */
            receivedAt?: string;
        };
        IngestedSpan: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            serviceId?: string;
            /** Format: uuid */
            environmentId?: null | string;
            /** Format: uuid */
            versionId?: string;
            traceId: string;
            spanId: string;
            parentSpanId?: null | string;
            name: string;
            /** Format: int32 */
            kind?: number | string;
            /** Format: int64 */
            startUnixNano?: number | string;
            /** Format: int64 */
            endUnixNano?: number | string;
            /** Format: int64 */
            durationNano?: number | string;
            /** Format: int32 */
            statusCode?: number | string;
            statusMessage?: null | string;
            instanceId?: string;
            attributes?: {
                [key: string]: string;
            };
            receiptId: string;
            /** Format: date-time */
            receivedAt?: string;
        };
        LatencyPercentiles: {
            /** Format: int64 */
            count: number | string;
            /** Format: double */
            p50: number | string;
            /** Format: double */
            p95: number | string;
            /** Format: double */
            p99: number | string;
        };
        MeResponse: {
            subjectId: string;
            authenticated: boolean;
        };
        OperationStat: {
            operation: string;
            /** Format: int64 */
            count: number | string;
            /** Format: int64 */
            errorCount: number | string;
        };
        TraceView: {
            spans: components["schemas"]["IngestedSpan"][];
            logs: components["schemas"]["IngestedLog"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    ProjectLatency: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyPercentiles"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectOperations: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
                limit: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationStat"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
