/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpaConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IngestReplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IngestClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enforcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Enforcement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SaveChannelConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SaveChannelRouting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{type}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/allow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AllowUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StorageHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectLatency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IssueSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListReplaySessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReplaySessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IssueCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/{issueId}/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IssueCorrelation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/{issueId}/stacktrace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IssueStackTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/traces/{traceId}/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceCorrelation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/sessions/{sessionId}/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionCorrelation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/issues/{issueId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SetIssueStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertEventView: {
            kind: string;
            /** Format: uuid */
            issueId: string;
            title: string;
            /** Format: date-time */
            atUtc: string;
        };
        AlertKindView: {
            key: string;
            name: string;
            planned: boolean;
        };
        AlertRuleView: {
            id: string;
            name: string;
            enabled: boolean;
        };
        AlertsView: {
            rules: components["schemas"]["AlertRuleView"][];
            history: components["schemas"]["AlertEventView"][];
        };
        AllowUserRequest: {
            email: string;
            role: null | string;
        };
        ChannelConfigUpdate: {
            smtp: null | components["schemas"]["SmtpUpdate"];
            slack: null | components["schemas"]["SlackUpdate"];
            telegram: null | components["schemas"]["TelegramUpdate"];
        };
        ChannelConfigView: {
            type: string;
            label: string;
            reachback: boolean;
            outsideHost: null | string;
            allowedUnderMode: boolean;
            enabled: boolean;
            configured: boolean;
            fields: components["schemas"]["ChannelFieldView"][];
            lastTest: null | components["schemas"]["ChannelTestView"];
        };
        ChannelFieldView: {
            key: string;
            label: string;
            value: null | string;
            secret: boolean;
            set: boolean;
            placeholder: null | string;
        };
        ChannelsView: {
            mode: string;
            reachbackAllowed: boolean;
            channels: components["schemas"]["ChannelConfigView"][];
            alertKinds: components["schemas"]["AlertKindView"][];
            routing: components["schemas"]["RoutingRow"][];
        };
        ChannelTestView: {
            /** Format: date-time */
            atUtc: string;
            ok: boolean;
            /** Format: int64 */
            ms: number | string;
            error: null | string;
        };
        ClientEvent: {
            kind: null | string;
            level: null | string;
            message: string;
            url: null | string;
            /** Format: int32 */
            status: null | number | string;
            stack: null | string;
            /** Format: int64 */
            atUnixMs: null | number | string;
        };
        ClientTelemetryRequest: {
            sessionId: null | string;
            userAgent: null | string;
            events: components["schemas"]["ClientEvent"][];
        };
        ComponentHealth: {
            name: string;
            subtitle: string;
            status: string;
            runningDesired: null | string;
            /** Format: double */
            cpuMillicores: null | number | string;
            /** Format: int64 */
            memoryBytes: null | number | string;
            /** Format: int32 */
            restarts: null | number | string;
            uptime: null | string;
        };
        CorrelationView: {
            /** Format: uuid */
            issueId: null | string;
            errorType: null | string;
            /** Format: int64 */
            atUnixNano: null | number | string;
            traceId: null | string;
            spanId: null | string;
            sessionId: null | string;
            trace: null | components["schemas"]["TraceSummary"];
            logs: null | components["schemas"]["LogsOnTrace"];
            replay: null | components["schemas"]["ReplayLink"];
        };
        DuckTier: {
            enabled: boolean;
            store: string;
        };
        EnforcementView: {
            mode: string;
            locked: boolean;
        };
        HealthKpis: {
            /** Format: double */
            ingestRatePerSec: null | number | string;
            /** Format: double */
            freshnessP95Sec: null | number | string;
            /** Format: int64 */
            bufferedPending: number | string;
            dominantStream: null | string;
            /** Format: int64 */
            dropped24h: number | string;
            /** Format: int64 */
            rejected24h: number | string;
            /** Format: int64 */
            deadLetters: number | string;
        };
        HealthView: {
            overallStatus: string;
            overallMessage: null | string;
            kpis: components["schemas"]["HealthKpis"];
            pipeline: components["schemas"]["PipelineStage"][];
            valkey: null | components["schemas"]["ValkeyHealth"];
            postgres: null | components["schemas"]["PgTier"];
            duck: components["schemas"]["DuckTier"];
            clickHouseConfigured: boolean;
            components: components["schemas"]["ComponentHealth"][];
        };
        IngestedLog: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            serviceId?: string;
            /** Format: uuid */
            environmentId?: null | string;
            /** Format: uuid */
            versionId?: string;
            /** Format: int64 */
            timeUnixNano?: number | string;
            /** Format: int32 */
            severityNumber?: number | string;
            severityText?: null | string;
            body?: null | string;
            traceId?: null | string;
            spanId?: null | string;
            instanceId?: string;
            attributes?: {
                [key: string]: string;
            };
            fingerprint?: null | string;
            receiptId: string;
            /** Format: date-time */
            receivedAt?: string;
        };
        IngestedSpan: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            serviceId?: string;
            /** Format: uuid */
            environmentId?: null | string;
            /** Format: uuid */
            versionId?: string;
            traceId: string;
            spanId: string;
            parentSpanId?: null | string;
            name: string;
            /** Format: int32 */
            kind?: number | string;
            /** Format: int64 */
            startUnixNano?: number | string;
            /** Format: int64 */
            endUnixNano?: number | string;
            /** Format: int64 */
            durationNano?: number | string;
            /** Format: int32 */
            statusCode?: number | string;
            statusMessage?: null | string;
            instanceId?: string;
            attributes?: {
                [key: string]: string;
            };
            fingerprint?: null | string;
            receiptId: string;
            /** Format: date-time */
            receivedAt?: string;
        };
        Issue: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            /** Format: uuid */
            serviceId?: string;
            fingerprint: string;
            title: string;
            errorType?: null | string;
            status?: components["schemas"]["IssueStatus"];
            /** Format: int64 */
            count?: number | string;
            /** Format: date-time */
            firstSeenAtUtc?: string;
            /** Format: date-time */
            lastSeenAtUtc?: string;
            /** Format: int64 */
            firstSeenVersionSequence?: number | string;
            /** Format: int64 */
            lastSeenVersionSequence?: number | string;
            /** Format: int64 */
            resolvedInVersionSequence?: null | number | string;
            affectedVersionSequences?: (number | string)[];
        };
        IssueCounts: {
            /** Format: int32 */
            unresolved: number | string;
            /** Format: int32 */
            regressed: number | string;
            /** Format: int32 */
            resolved: number | string;
            /** Format: int32 */
            muted: number | string;
            /** Format: int32 */
            total: number | string;
        };
        IssueSeries: {
            fingerprint: string;
            buckets: (number | string)[];
            /** Format: int32 */
            sessions: number | string;
        };
        IssueStatus: number;
        IssueStatusRequest: {
            status: string;
            /** Format: int64 */
            resolvedInVersionSequence: null | number | string;
        };
        JsonElement: unknown;
        LatencyPercentiles: {
            /** Format: int64 */
            count: number | string;
            /** Format: double */
            p50: number | string;
            /** Format: double */
            p95: number | string;
            /** Format: double */
            p99: number | string;
        };
        LogsOnTrace: {
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            errorCount: number | string;
            /** Format: int32 */
            warnCount: number | string;
            topMessage: null | string;
        };
        MeResponse: {
            subjectId: string;
            email: string;
            admitted: boolean;
            role: null | string;
            capabilities: string[];
        };
        OperationStat: {
            operation: string;
            /** Format: int64 */
            count: number | string;
            /** Format: int64 */
            errorCount: number | string;
        };
        PgTier: {
            /** Format: int32 */
            connections: number | string;
            /** Format: int32 */
            maxConnections: number | string;
            /** Format: int64 */
            dbSizeBytes: number | string;
            /** Format: double */
            cacheHitRatio: number | string;
            version: string;
            largestTables: components["schemas"]["TableSize"][];
        };
        PipelineStage: {
            name: string;
            status: string;
            facts: string[];
            tag: null | string;
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
        };
        ReplayChunkRequest: {
            sessionId: string;
            startUrl: null | string;
            userAgent: null | string;
            events: components["schemas"]["JsonElement"];
        };
        ReplayLink: {
            sessionId: string;
            available: boolean;
            /** Format: int32 */
            eventCount: number | string;
        };
        ReplaySessionSummary: {
            sessionId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            lastEventAtUtc: string;
            /** Format: int32 */
            eventCount: number | string;
            /** Format: int64 */
            payloadBytes: number | string;
            startUrl: null | string;
            userAgent: null | string;
        };
        RoutingRow: {
            kind: string;
            channels: string[];
        };
        RoutingUpdate: {
            rows: components["schemas"]["RoutingRow"][];
        };
        SeriesBucket: {
            /** Format: int64 */
            startUnixNano: number | string;
            /** Format: int64 */
            count: number | string;
            /** Format: int64 */
            errorCount: number | string;
        };
        ServiceSummary: {
            /** Format: uuid */
            id: string;
            serviceName: string;
            namespace: null | string;
        };
        SlackUpdate: {
            enabled: boolean;
            webhookUrl: null | string;
        };
        SmtpUpdate: {
            enabled: boolean;
            host: null | string;
            from: null | string;
            to: null | string;
        };
        StackFrameView: {
            function: string;
            file: null | string;
            /** Format: int32 */
            line: null | number | string;
            inApp: boolean;
        };
        StackTraceView: {
            errorType: null | string;
            message: null | string;
            symbolicated: boolean;
            source: null | string;
            frames: components["schemas"]["StackFrameView"][];
            raw: null | string;
        };
        StorageHealth: {
            writeStore: string;
            readStore: string;
            clickHouseConfigured: boolean;
        };
        StreamStat: {
            name: string;
            /** Format: int64 */
            length: number | string;
            /** Format: int64 */
            pending: number | string;
            /** Format: double */
            lagSeconds: null | number | string;
            /** Format: int32 */
            consumers: number | string;
            /** Format: int32 */
            consumersExpected: number | string;
            status: string;
        };
        TableSize: {
            name: string;
            /** Format: int64 */
            bytes: number | string;
        };
        TelegramUpdate: {
            enabled: boolean;
            botToken: null | string;
            chatId: null | string;
        };
        TraceSummary: {
            rootOperation: string;
            /** Format: int64 */
            durationNano: number | string;
            /** Format: int32 */
            spanCount: number | string;
            /** Format: int32 */
            serviceCount: number | string;
            /** Format: int32 */
            errorSpanCount: number | string;
        };
        TraceView: {
            spans: components["schemas"]["IngestedSpan"][];
            logs: components["schemas"]["IngestedLog"][];
        };
        UserView: {
            email: string;
            role: string;
            /** Format: date-time */
            createdAtUtc: string;
        };
        ValkeyHealth: {
            server: components["schemas"]["ValkeyServer"];
            streams: components["schemas"]["StreamStat"][];
            /** Format: int32 */
            laggingCount: number | string;
        };
        ValkeyServer: {
            /** Format: int64 */
            usedMemoryBytes: number | string;
            /** Format: int64 */
            maxMemoryBytes: number | string;
            evictionPolicy: string;
            persistence: string;
            /** Format: int64 */
            opsPerSec: number | string;
            /** Format: int32 */
            clients: number | string;
            version: string;
            /** Format: double */
            uptimeDays: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpaConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngestReplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayChunkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngestClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientTelemetryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    ListProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    ListServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceSummary"][];
                };
            };
        };
    };
    Enforcement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementView"];
                };
            };
        };
    };
    Channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaveChannelConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaveChannelRouting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTestView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AllowUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StorageHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageHealth"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectLatency: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyPercentiles"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectSeries: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
                buckets?: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesBucket"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IssueSeries: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                buckets?: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueSeries"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectOperations: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
                limit: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationStat"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListReplaySessions: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySessionSummary"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReplaySessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListIssues: {
        parameters: {
            query?: {
                status?: string;
                service?: string;
                limit?: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IssueCounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueCounts"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IssueCorrelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IssueStackTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackTraceView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TraceCorrelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionCorrelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SetIssueStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueStatusRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectLogs: {
        parameters: {
            query: {
                start: number | string;
                end: number | string;
                service?: string;
                minSeverity?: number | string;
                limit?: number | string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestedLog"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
