<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tamp.Observer.RawBucket.Abstractions</RootNamespace>
    <AssemblyName>Tamp.Observer.RawBucket.Abstractions</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
