<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tamp.Observer.Storage.ClickHouse</RootNamespace>
    <AssemblyName>Tamp.Observer.Storage.ClickHouse</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tamp.Observer.Domain\Tamp.Observer.Domain.csproj" />
    <ProjectReference Include="..\Tamp.Observer.Storage.Abstractions\Tamp.Observer.Storage.Abstractions.csproj" />
  </ItemGroup>

</Project>
